############################
# APPLICATION
############################
spring.application.name=meeting-room-booking-service
server.port=8095

############################
# ACTUATOR
############################
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

############################
# LOGGING
############################
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

############################
# JACKSON
############################
spring.jackson.parser.allow-unquoted-field-names=true
