spring.application.name=api-gateway
server.port=8090

# Backend services
auth.service.url=http://localhost:8091
setting.service.url=http://localhost:8092

# JWT (must match auth_service secret)
jwt.secret=ChangeThisSecretToSomethingLongerAndSafer123!

# Spring Cloud Gateway (MVC) routes
spring.cloud.gateway.server.webmvc.routes[0].id=auth-api
spring.cloud.gateway.server.webmvc.routes[0].uri=${auth.service.url}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=auth-sso
spring.cloud.gateway.server.webmvc.routes[1].uri=${auth.service.url}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/auth/sso/**

spring.cloud.gateway.server.webmvc.routes[2].id=setting-api
spring.cloud.gateway.server.webmvc.routes[2].uri=${setting.service.url}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/setting/**
